services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-converter-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: file-converter-db
    environment:
      MYSQL_DATABASE: file_converter
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: